# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
