#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Missing arguments, exiting"
    echo "For help do: ./fileapi -h or ./fileapi --help"
    exit 1
fi

_help="\

    A tools to help set up the file-api.

    Options:
    ~~~~~~~

        -t, --tests     Run integration tests.
        -g, --guide     Setup instructions.
        -h, --help      Print this help.

    Usage:
    ~~~~~

        fileapi [option]

"

_guide="\

    Help guide for setting up the file API after installation.


    Setup instructions:
    ~~~~~~~~~~~~~~~~~~

    1. Create a config file

        cp /etc/opt/file-api-config.yaml.example /etc/opt/file-api-config.yaml
        chown fileapi:fileapi /etc/opt/file-api-config.yaml

    2. Fill in the correct values

        emacs /etc/opt/file-api-config.yaml

    3. Create the default file upload directory

        mkdir /opt/file-api-uploads && chown fileapi:fileapi /opt/file-api-uploads

    4. Start the service, check its status

        systemctl start file-api
        systemctl status file-api

    5. Run tests to verify it works

        fileapi -t

"

VENV_PYTHON=/opt/tsd-file-api-env/bin/python
MODULE_DIR=/opt/tsd-file-api-env/lib/python2.7/site-packages/tsdfileapi
CONFIG_FILE=/etc/opt/file-api-config.yaml

tests() {
    $VENV_PYTHON $MODULE_DIR/tests/test_file_api.py $CONFIG_FILE
}

while (( "$#" )); do
    case $1 in
        -t | --tests)           shift; tests; exit 0 ;;
        -g | --guide)           printf "%s\n" "$_guide"; exit 0 ;;
        -h | --help)            printf "%s\n" "$_help"; exit 0 ;;
        *) break ;;
    esac
done
