ARG PYTHON_VERSION=3
FROM docker.io/python:${PYTHON_VERSION}

RUN apt-get update
RUN apt-get install -y libsodium23 libmagic1 sudo
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry self add "poetry-dynamic-versioning[plugin]"

RUN groupadd p11-member-group
RUN groupadd p12-member-group
WORKDIR /file-api

COPY . ./
RUN poetry install --no-interaction
